### PR TITLE
Disables the body scrolling when the modal is toggled on

### LINKED ISSUE #463: Modal body scroll not locked
**Describe the bug**
The body scroll is not locked when modal is visible 

**To Reproduce**
create a modal on a scrollable page

**Expected behavior**
The modal should lock the scroll in the background

**Screenshots**
modal-scrolling

### PR DESCRIPTION
**Pull request by yousifalraheem**
fixes #463

### CODE REVIEW

File: projects/ng-components/lib/modal/modal.component.ts [hunk 1]
```diff
@@ -64,6 +64,12 @@ export class ModalComponent implements OnDestroy {
             if (toggle && this.hidden) {
                 this.hidden = false;
             }
+
+            if (toggle) {
+                document.body.classList.add("overflow-hidden");
+            } else {
+                document.body.classList.remove("overflow-hidden");
+            }
```
Comment (kherP) [inline projects/ng-components/lib/modal/modal.component.ts:72]: suggested change for this whole block
```
if (toggle && this.escapeToDismiss) {
                window.addEventListener("keyup", this.escapeKeyListener);
            }

            // Unsubscribe as soon as the the modal is dismissed
            if (!toggle && this.escapeToDismiss) {
                window.removeEventListener("keyup", this.escapeKeyListener);
            }

            // This only runs once when the toggle value is changed
            if (toggle && this.hidden) {
                this.hidden = false;
            }

            if (toggle) {
                document.body.classList.add("overflow-hidden");
            } else {
                document.body.classList.remove("overflow-hidden");
            }
```

to this:
```
if (toggle) {
            this.escapeToDismiss && window.addEventListener("keyup", this.escapeKeyListener);
            document.body.classList.add("overflow-hidden");
            this.hidden = false;
        } else {
            // Unsubscribe as soon as the the modal is dismissed
            this.escapeToDismiss && window.removeEventListener("keyup", this.escapeKeyListener);
            document.body.classList.remove("overflow-hidden");
        }
