### PR TITLE
fix: tooltip content not showing, Add support for click in small …devices even if the toggle isnt

### LINKED ISSUE #524: Tooltip not showing content in v1.0.0-beta.12
**Describe the bug**
After updating version from v1.0.0-beta.10 to v1.0.0-beta.12 stopped seeing content what tooltip represents.

**To Reproduce**
```
 <sebng-tooltip [content]="'tooltip text">
        <sebng-checkbox ...>
        </sebng-checkbox>
 </sebng-tooltip>

```
**Expected behavior**
Expected to see checkbox and tooltip on hover.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by omarVodiaK**
fix #524

### CODE REVIEW

File: projects/ng-components/lib/tooltip/tooltip.directive.ts [hunk 1]
```diff
@@ -174,6 +177,22 @@ export class TooltipDirective implements OnDestroy {
         this.overlayRef?.dispose();
     }
 
+    /**
+     * <!-- skip -->
+     * Detect device type
+     * @returns DeviceType (desktop, mobile ipad)
+     */
+    get deviceType(): DeviceType {
+        const ua = navigator.userAgent;
```
Comment (kherP) [inline projects/ng-components/lib/tooltip/tooltip.directive.ts:186]: missing ua type 😄

**Review by kherP — APPROVED** [review]

**Review by yousifalraheem — APPROVED** [review]
